In [1]:
import numpy as np
import pandas as pd
import re
import nltk
import string
pd.options.mode.chained_assignment = None

In [2]:
import os
os.getcwd()

'C:\\Users\\JiatingChen\\Documents\\nlp-coe\\twitter-conversational-chatbot\\EDA Notebooks'

In [3]:
os.listdir('C:\\Users\\JiatingChen\\Documents\\archive\\twcs')

['twcs.csv']

In [7]:
tweets = pd.read_csv("C:\\Users\\JiatingChen\\Documents\\archive\\twcs\\twcs.csv")

In [8]:
tweets["text"] = tweets["text"].astype(str)

In [9]:
tweets.shape #2,811,774

(2811774, 7)

In [10]:
tweets.sort_values('tweet_id').head(20)

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist y...,2,3.0
1,2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messag...,1,4.0
3,4,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so th...,3,5.0
4,5,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0
5,6,sprintcare,False,Tue Oct 31 21:46:24 +0000 2017,@115712 Can you please send us a private messa...,"5,7",8.0
2314173,7,115712,True,Tue Oct 31 21:47:48 +0000 2017,@sprintcare the only way I can get a response ...,NaN,6.0
6,8,115712,True,Tue Oct 31 21:45:10 +0000 2017,@sprintcare is the worst customer service,"9,6,10",NaN
2314166,9,sprintcare,False,Tue Oct 31 21:46:14 +0000 2017,@115712 I would love the chance to review the ...,NaN,8.0
2314174,10,sprintcare,False,Tue Oct 31 21:45:59 +0000 2017,@115712 Hello! We never like our customers to ...,NaN,8.0
7,11,sprintcare,False,Tue Oct 31 22:10:35 +0000 2017,@115713 This is saddening to hear. Please shoo...,NaN,12.0
8,12,115713,True,Tue Oct 31 22:04:47 +0000 2017,@sprintcare You gonna magically change your co...,"11,13,14",15.0
48297,13,sprintcare,False,Wed Nov 01 20:48:14 +0000 2017,@115713 I would really like to work with you t...,NaN,12.0
2375616,14,sprintcare,False,Wed Nov 01 20:47:40 +0000 2017,"@115713 Hi, my name is Shantel, I'm a resoluti...",NaN,12.0
9,15,sprintcare,False,Tue Oct 31 20:03:31 +0000 2017,@115713 We understand your concerns and we'd l...,12,16.0
10,16,115713,True,Tue Oct 31 20:00:43 +0000 2017,@sprintcare Since I signed up with you....Sinc...,15,17.0
11,17,sprintcare,False,Tue Oct 31 19:59:13 +0000 2017,@115713 H there! We'd definitely like to work ...,16,18.0
12,18,115713,True,Tue Oct 31 19:56:01 +0000 2017,@115714 y’all lie about your “great” connectio...,17,NaN
13,19,sprintcare,False,Tue Oct 31 22:10:10 +0000 2017,@115715 Please send me a private message so th...,NaN,20.0
14,20,115715,True,Tue Oct 31 22:03:34 +0000 2017,"@115714 whenever I contact customer support, t...",19,NaN

In [11]:
# in_response_tweet_id = 1: tweet_id = 1 is the prior sentense
# response_tweet_id = 1: tweet_id = 1 is the next sentense

In [15]:
first_inbound = tweets[pd.isnull(tweets.in_response_to_tweet_id)] #initize the conversation
inbounds_and_outbounds = pd.merge(first_inbound, tweets, left_on='tweet_id', 
                                  right_on='in_response_to_tweet_id') 
inbounds_and_outbounds.sort_values(['tweet_id_x', 'created_at_y'], ascending= [True, True]).shape #895,514 back-and-forth dialog

(895514, 14)

In [18]:
inbounds_and_outbounds.head(100).created_at_y = pd.to_datetime(inbounds_and_outbounds.head(100).created_at_y)

In [19]:
inbounds_and_outbounds.head(100).sort_values(['tweet_id_x', 'created_at_y'], ascending= [True, True])

,tweet_id_x,author_id_x,inbound_x,created_at_x,text_x,response_tweet_id_x,in_response_to_tweet_id_x,tweet_id_y,author_id_y,inbound_y,created_at_y,text_y,response_tweet_id_y,in_response_to_tweet_id_y
2,8,115712,True,Tue Oct 31 21:45:10 +0000 2017,@sprintcare is the worst customer service,"9,6,10",NaN,10,sprintcare,False,Tue Oct 31 21:45:59 +0000 2017,@115712 Hello! We never like our customers to ...,NaN,8.0
1,8,115712,True,Tue Oct 31 21:45:10 +0000 2017,@sprintcare is the worst customer service,"9,6,10",NaN,9,sprintcare,False,Tue Oct 31 21:46:14 +0000 2017,@115712 I would love the chance to review the ...,NaN,8.0
0,8,115712,True,Tue Oct 31 21:45:10 +0000 2017,@sprintcare is the worst customer service,"9,6,10",NaN,6,sprintcare,False,Tue Oct 31 21:46:24 +0000 2017,@115712 Can you please send us a private messa...,"5,7",8.0
3,18,115713,True,Tue Oct 31 19:56:01 +0000 2017,@115714 y’all lie about your “great” connectio...,17,NaN,17,sprintcare,False,Tue Oct 31 19:59:13 +0000 2017,@115713 H there! We'd definitely like to work ...,16,18.0
4,20,115715,True,Tue Oct 31 22:03:34 +0000 2017,"@115714 whenever I contact customer support, t...",19,NaN,19,sprintcare,False,Tue Oct 31 22:10:10 +0000 2017,@115715 Please send me a private message so th...,NaN,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,320,115789,True,Tue Oct 31 21:17:16 +0000 2017,@115790 @XboxSupport redeemed a code for fifa ...,319,NaN,319,XboxSupport,False,Tue Oct 31 22:12:17 +0000 2017,@115789 Hello! Would you mind following us and...,NaN,320.0
96,323,115791,True,Tue Oct 31 19:39:09 +0000 2017,@1520 @XboxSupport the 5 app on Xboxes not wo...,321,NaN,321,XboxSupport,False,Tue Oct 31 22:03:03 +0000 2017,@115791 Can you show us what is appearing on y...,322,323.0
97,325,115792,True,Wed Nov 22 08:55:35 +0000 2017,amazonプライムビデオ、再生エラーが多いです,324,NaN,324,AmazonHelp,False,Wed Nov 22 09:06:00 +0000 2017,@115792 ご不便をおかけしております。アプリをご利用でしょうか。強制停止&gt;端末の...,NaN,325.0
98,331,115795,True,Tue Oct 31 21:48:40 +0000 2017,Something going on at Preston train station ? ...,330,NaN,330,115794,True,Tue Oct 31 21:55:35 +0000 2017,@115795 @115796 What have you seen?,329,331.0
99,348,115798,True,Mon Aug 29 03:20:05 +0000 2011,"Lost your booking number? No worries, just dro...","349,350,351,352,347,353,354,355,356,357,358,35...",NaN,347,115797,True,Tue Oct 31 01:57:03 +0000 2017,@AirAsiaSupport lost my booking # chua loreen ...,343,348.0

In [21]:
inbounds_and_outbounds.head(100).sort_values(['tweet_id_x', 'created_at_y'], ascending= [True, True])[['text_x', 'text_y']].head(100).to_csv('conv.txt', index = False)

In [ ]:
inbounds_and_outbounds.head()

In [ ]:
inbounds_and_outbounds[['text_x', 'text_y']].head(100).to_csv('conv.txt')

In [ ]:
first_inbound2 = tweets[pd.isnull(tweets.in_response_to_tweet_id) & tweets.inbound]
inbounds_and_outbounds = pd.merge(first_inbound2, tweets, left_on='tweet_id', 
                                  right_on='in_response_to_tweet_id') #.sample(frac=1)
inbounds_and_outbounds2 = inbounds_and_outbounds[inbounds_and_outbounds.inbound_y ^ True]
inbounds_and_outbounds2.sort_values('tweet_id_x').shape #794,299 back-and-forth dialog responded from companies

## citation: https://www.kaggle.com/soaxelbrooke/twitter-basic-seq2seq
## next step 1 - text preprocessing
- Lower casing
- Removal of Punctuations
- Removal of Stopwords
- Removal of Frequent words
- Removal of Rare words
- Stemming
- Lemmatization
- Removal of emojis
- Removal of emoticons
- Conversion of emoticons to words
- Conversion of emojis to words
- Removal of URLs
- Removal of HTML tags
- Chat words conversion
- Spelling correction

## next step 2 - build virtualenv for all necessary packages